name: Unzip File in Repo

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Unzip the file
        run: |
          unzip your-file.zip -d extracted_files
          rm your-file.zip

      - name: Commit unzipped content
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add extracted_files
          git commit -m "Unzip file and add contents"
          git push 
